---
title: "Leaflet"
author: "Miranda Lupion"
date: "10/16/2018"
output: html_document
---


```{r setup, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE, cache = TRUE}
knitr::opts_chunk$set(echo = FALSE)
library(leaflet)
library(tidyverse)
library(rgdal)
crime <- read_rds("r_4_tidy.rds")

crime <- crime %>%
  filter(YEAR == 2000)


rf_map <- readOGR(dsn = "/Users/MLupion/Desktop/GOV 1005/GOV_1005_Final_Project/RUS_adm", layer = "RUS_adm1")

rf_map <- spTransform(rf_map, CRS("+init=epsg:4326"))

rf_map <- merge(rf_map, crime, by = "ID_1", duplicateGeoms = TRUE)

coloring <- colorNumeric(palette = "Blues",
                         domain = rf_map@data$CRIMESHARE)

```


```{r leaflet code}
rf_map %>%
  leaflet(options = leafletOptions(dragging = TRUE)) %>%
  addProviderTiles(provider = "CartoDB") %>%
  setView(lng = 37.618423, lat = 55.751244, zoom = 3) %>%
  setMaxBounds(lng1 = 40, lat1 = 30, lng2 = 150, lat2 = 100) %>%
  addPolygons(weight = 1, 
              label = ~paste0(NAME, ", ", CRIMESHARE),
              color = ~coloring(CRIMESHARE)) %>%
  addLegend("bottomright", pal = coloring, values = ~CRIMESHARE,
            title = "title here",
            opacity = 1)

```


